In [1]:
import tensorflow as tf
import pandas as pd

In [2]:


df=pd.read_csv('NF-UQ-NIDS-v2.csv',nrows=100000)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   IPV4_SRC_ADDR                100000 non-null  object
 1   L4_SRC_PORT                  100000 non-null  int64
 2   IPV4_DST_ADDR                100000 non-null  object
 3   L4_DST_PORT                  100000 non-null  int64
 4   PROTOCOL                     100000 non-null  int64
 5   L7_PROTO                     100000 non-null  float64
 6   IN_BYTES                     100000 non-null  int64
 7   IN_PKTS                      100000 non-null  int64
 8   OUT_BYTES                    100000 non-null  int64
 9   OUT_PKTS                     100000 non-null  int64
 10  TCP_FLAGS                    100000 non-null  int64
 11  CLIENT_TCP_FLAGS             100000 non-null  int64
 12  SERVER_TCP_FLAGS             100000 non-null  int64
 13  FLOW_DURATION_MILLISECONDS   100000 non-null  int64
 14  DURATION_IN                  100000 non-null  int64
 15  DURATION_OUT                 100000 non-null  int64
 16  MIN_TTL                      100000 non-null  int64
 17  MAX_TTL                      100000 non-null  int64
 18  LONGEST_FLOW_PKT             100000 non-null  int64
 19  SHORTEST_FLOW_PKT            100000 non-null  int64
 20  MIN_IP_PKT_LEN               100000 non-null  int64
 21  MAX_IP_PKT_LEN               100000 non-null  int64
 22  SRC_TO_DST_SECOND_BYTES      100000 non-null  float64
 23  DST_TO_SRC_SECOND_BYTES      100000 non-null  float64
 24  RETRANSMITTED_IN_BYTES       100000 non-null  int64
 25  RETRANSMITTED_IN_PKTS        100000 non-null  int64
 26  RETRANSMITTED_OUT_BYTES      100000 non-null  int64
 27  RETRANSMITTED_OUT_PKTS       100000 non-null  int64
 28  SRC_TO_DST_AVG_THROUGHPUT    100000 non-null  int64
 29  DST_TO_SRC_AVG_THROUGHPUT    100000 non-null  int64
 30  NUM_PKTS_UP_TO_128_BYTES     100000 non-null  int64
 31  NUM_PKTS_128_TO_256_BYTES    100000 non-null  int64
 32  NUM_PKTS_256_TO_512_BYTES    100000 non-null  int64
 33  NUM_PKTS_512_TO_1024_BYTES   100000 non-null  int64
 34  NUM_PKTS_1024_TO_1514_BYTES  100000 non-null  int64
 35  TCP_WIN_MAX_IN               100000 non-null  int64
 36  TCP_WIN_MAX_OUT              100000 non-null  int64
 37  ICMP_TYPE                    100000 non-null  int64
 38  ICMP_IPV4_TYPE               100000 non-null  int64
 39  DNS_QUERY_ID                 100000 non-null  int64
 40  DNS_QUERY_TYPE               100000 non-null  int64
 41  DNS_TTL_ANSWER               100000 non-null  int64
 42  FTP_COMMAND_RET_CODE         100000 non-null  float64
 43  Label                        100000 non-null  int64
 44  Attack                       100000 non-null  object
 45  Dataset                      100000 non-null  object
dtypes: float64(4), int64(38), object(4)
memory usage: 35.1+ MB

In [3]:
df.head()

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,...,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack,Dataset
0,192.168.100.148,65389,192.168.100.7,80,6,7.0,420,3,0,0,...,0,35840,140,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2
1,192.168.100.148,11154,192.168.100.5,80,6,7.0,280,2,40,1,...,0,0,0,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2
2,192.168.1.31,42062,192.168.1.79,1041,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2
3,192.168.1.34,46849,192.168.1.79,9110,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2
4,192.168.1.30,50360,192.168.1.152,1084,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2

In [4]:
df.fillna(value='', inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   IPV4_SRC_ADDR                100000 non-null  object
 1   L4_SRC_PORT                  100000 non-null  int64
 2   IPV4_DST_ADDR                100000 non-null  object
 3   L4_DST_PORT                  100000 non-null  int64
 4   PROTOCOL                     100000 non-null  int64
 5   L7_PROTO                     100000 non-null  float64
 6   IN_BYTES                     100000 non-null  int64
 7   IN_PKTS                      100000 non-null  int64
 8   OUT_BYTES                    100000 non-null  int64
 9   OUT_PKTS                     100000 non-null  int64
 10  TCP_FLAGS                    100000 non-null  int64
 11  CLIENT_TCP_FLAGS             100000 non-null  int64
 12  SERVER_TCP_FLAGS             100000 non-null  int64
 13  FLOW_DURATION_MILLISECONDS   100000 non-null  int64
 14  DURATION_IN                  100000 non-null  int64
 15  DURATION_OUT                 100000 non-null  int64
 16  MIN_TTL                      100000 non-null  int64
 17  MAX_TTL                      100000 non-null  int64
 18  LONGEST_FLOW_PKT             100000 non-null  int64
 19  SHORTEST_FLOW_PKT            100000 non-null  int64
 20  MIN_IP_PKT_LEN               100000 non-null  int64
 21  MAX_IP_PKT_LEN               100000 non-null  int64
 22  SRC_TO_DST_SECOND_BYTES      100000 non-null  float64
 23  DST_TO_SRC_SECOND_BYTES      100000 non-null  float64
 24  RETRANSMITTED_IN_BYTES       100000 non-null  int64
 25  RETRANSMITTED_IN_PKTS        100000 non-null  int64
 26  RETRANSMITTED_OUT_BYTES      100000 non-null  int64
 27  RETRANSMITTED_OUT_PKTS       100000 non-null  int64
 28  SRC_TO_DST_AVG_THROUGHPUT    100000 non-null  int64
 29  DST_TO_SRC_AVG_THROUGHPUT    100000 non-null  int64
 30  NUM_PKTS_UP_TO_128_BYTES     100000 non-null  int64
 31  NUM_PKTS_128_TO_256_BYTES    100000 non-null  int64
 32  NUM_PKTS_256_TO_512_BYTES    100000 non-null  int64
 33  NUM_PKTS_512_TO_1024_BYTES   100000 non-null  int64
 34  NUM_PKTS_1024_TO_1514_BYTES  100000 non-null  int64
 35  TCP_WIN_MAX_IN               100000 non-null  int64
 36  TCP_WIN_MAX_OUT              100000 non-null  int64
 37  ICMP_TYPE                    100000 non-null  int64
 38  ICMP_IPV4_TYPE               100000 non-null  int64
 39  DNS_QUERY_ID                 100000 non-null  int64
 40  DNS_QUERY_TYPE               100000 non-null  int64
 41  DNS_TTL_ANSWER               100000 non-null  int64
 42  FTP_COMMAND_RET_CODE         100000 non-null  float64
 43  Label                        100000 non-null  int64
 44  Attack                       100000 non-null  object
 45  Dataset                      100000 non-null  object
dtypes: float64(4), int64(38), object(4)
memory usage: 35.1+ MB

In [29]:
df['IPV4_DST_ADDR'] = df['IPV4_DST_ADDR'].apply(lambda ip: int(ip.replace('.', '')))
df['IPV4_SRC_ADDR'] = df['IPV4_SRC_ADDR'].apply(lambda ip: int(ip.replace('.', '')))

In [31]:
df.head(2)

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,...,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack,Dataset
0,192168100148,65389,1921681007,80,6,7.0,420,3,0,0,...,0,35840,140,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2
1,192168100148,11154,1921681005,80,6,7.0,280,2,40,1,...,0,0,0,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2

In [33]:
x_columns=df.columns.drop('Attack')
x_columns=x_columns.drop('Dataset')

In [34]:
x=df[x_columns].values

In [70]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)

/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1544: RuntimeWarning: overflow encountered in multiply
  sqr = np.multiply(arr, arr, out=arr)
/opt/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:87: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

In [71]:
dummies=pd.get_dummies(df['Attack'])

In [72]:
outcomes=dummies.columns

In [73]:
outcomes

Index(['Analysis', 'Backdoor', 'Benign', 'Bot', 'Brute Force', 'DDoS', 'DoS',
       'Exploits', 'Fuzzers', 'Generic', 'Infilteration', 'Reconnaissance',
       'Shellcode', 'Theft', 'injection', 'mitm', 'password', 'ransomware',
       'scanning', 'xss'],
      dtype='object')

In [74]:
num_classes=len(outcomes)

In [75]:
y=dummies.values

In [84]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.20, shuffle = True, random_state=64)

In [77]:
#for stacking
x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(x, y1, test_size=0.20, shuffle = True, random_state=64)

NameError: name 'y1' is not defined

In [85]:
#model1

model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim=x.shape[1], bias_initializer="zeros", activation='relu'),
    tf.keras.layers.Dense(128, input_dim=x.shape[1], bias_initializer="zeros", activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(128, input_dim=x.shape[1], bias_initializer="zeros", activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(64, input_dim=x.shape[1],  bias_initializer="zeros", activation='relu'),
    tf.keras.layers.Dense(y.shape[1],activation='softmax')
    ])

In [86]:
model_1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 64)                2880

 dense_31 (Dense)            (None, 128)               8320

 dropout_12 (Dropout)        (None, 128)               0

 dense_32 (Dense)            (None, 128)               16512

 dropout_13 (Dropout)        (None, 128)               0

 dense_33 (Dense)            (None, 64)                8256

 dense_34 (Dense)            (None, 20)                1300

=================================================================
Total params: 37,268
Trainable params: 37,268
Non-trainable params: 0
_________________________________________________________________

In [87]:
#model 1
import datetime
model_1.compile(loss='categorical_crossentropy',metrics=['accuracy'], optimizer='adam')

log_dir_1 = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [88]:
monitor_1 = [
             tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=8, verbose=1, mode='auto',restore_best_weights=True),
             tf.keras.callbacks.TensorBoard(log_dir=log_dir_1, histogram_freq=1)
            ]

In [89]:
x

array([[1.92168100e+11, 6.53890000e+04, 1.92168101e+09, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.92168100e+11, 1.11540000e+04, 1.92168100e+09, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.92168131e+08, 4.20620000e+04, 1.92168179e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.92168100e+11, 5.04280000e+04, 1.92168100e+09, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.82185513e+09, 5.27380000e+04, 1.72316925e+08, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.12921072e+09, 5.35640000e+04, 1.72316778e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [90]:
history_1  = model_1.fit(x_train,y_train,validation_data=(x_test,y_test), callbacks=[monitor_1],verbose=2, batch_size=1024, epochs=100)

Epoch 1/100
79/79 - 1s - loss: 0.8776 - accuracy: 0.7713 - val_loss: 0.2585 - val_accuracy: 0.9364 - 646ms/epoch - 8ms/step
Epoch 2/100
79/79 - 0s - loss: 0.2332 - accuracy: 0.9376 - val_loss: 0.1780 - val_accuracy: 0.9579 - 340ms/epoch - 4ms/step
Epoch 3/100
79/79 - 0s - loss: 0.1763 - accuracy: 0.9513 - val_loss: 0.1520 - val_accuracy: 0.9600 - 339ms/epoch - 4ms/step
Epoch 4/100
79/79 - 0s - loss: 0.1528 - accuracy: 0.9566 - val_loss: 0.1406 - val_accuracy: 0.9632 - 337ms/epoch - 4ms/step
Epoch 5/100
79/79 - 0s - loss: 0.1400 - accuracy: 0.9597 - val_loss: 0.1320 - val_accuracy: 0.9635 - 336ms/epoch - 4ms/step
Epoch 6/100
79/79 - 0s - loss: 0.1291 - accuracy: 0.9623 - val_loss: 0.1263 - val_accuracy: 0.9689 - 342ms/epoch - 4ms/step
Epoch 7/100
79/79 - 0s - loss: 0.1238 - accuracy: 0.9646 - val_loss: 0.1216 - val_accuracy: 0.9689 - 342ms/epoch - 4ms/step
Epoch 8/100
79/79 - 0s - loss: 0.1158 - accuracy: 0.9664 - val_loss: 0.1190 - val_accuracy: 0.9700 - 336ms/epoch - 4ms/step
Epoch 9/100
79/79 - 0s - loss: 0.1127 - accuracy: 0.9675 - val_loss: 0.1168 - val_accuracy: 0.9720 - 335ms/epoch - 4ms/step
Epoch 10/100
79/79 - 0s - loss: 0.1098 - accuracy: 0.9683 - val_loss: 0.1118 - val_accuracy: 0.9730 - 332ms/epoch - 4ms/step
Epoch 11/100
79/79 - 0s - loss: 0.1036 - accuracy: 0.9711 - val_loss: 0.1134 - val_accuracy: 0.9725 - 341ms/epoch - 4ms/step
Epoch 12/100
79/79 - 0s - loss: 0.1017 - accuracy: 0.9706 - val_loss: 0.1091 - val_accuracy: 0.9732 - 342ms/epoch - 4ms/step
Epoch 13/100
79/79 - 0s - loss: 0.0999 - accuracy: 0.9710 - val_loss: 0.1092 - val_accuracy: 0.9737 - 343ms/epoch - 4ms/step
Epoch 14/100
79/79 - 0s - loss: 0.0966 - accuracy: 0.9717 - val_loss: 0.1068 - val_accuracy: 0.9758 - 338ms/epoch - 4ms/step
Epoch 15/100
79/79 - 0s - loss: 0.0953 - accuracy: 0.9728 - val_loss: 0.1084 - val_accuracy: 0.9770 - 339ms/epoch - 4ms/step
Epoch 16/100
79/79 - 0s - loss: 0.0933 - accuracy: 0.9729 - val_loss: 0.1114 - val_accuracy: 0.9756 - 343ms/epoch - 4ms/step
Epoch 17/100
79/79 - 0s - loss: 0.0911 - accuracy: 0.9737 - val_loss: 0.1097 - val_accuracy: 0.9772 - 331ms/epoch - 4ms/step
Epoch 18/100
79/79 - 0s - loss: 0.0903 - accuracy: 0.9742 - val_loss: 0.1094 - val_accuracy: 0.9761 - 338ms/epoch - 4ms/step
Epoch 19/100
79/79 - 0s - loss: 0.0896 - accuracy: 0.9747 - val_loss: 0.1047 - val_accuracy: 0.9760 - 329ms/epoch - 4ms/step
Epoch 20/100
79/79 - 0s - loss: 0.0897 - accuracy: 0.9742 - val_loss: 0.1069 - val_accuracy: 0.9779 - 331ms/epoch - 4ms/step
Epoch 21/100
79/79 - 0s - loss: 0.0870 - accuracy: 0.9753 - val_loss: 0.1055 - val_accuracy: 0.9754 - 330ms/epoch - 4ms/step
Epoch 22/100
79/79 - 0s - loss: 0.0849 - accuracy: 0.9757 - val_loss: 0.1065 - val_accuracy: 0.9791 - 327ms/epoch - 4ms/step
Epoch 23/100
79/79 - 0s - loss: 0.0838 - accuracy: 0.9765 - val_loss: 0.1078 - val_accuracy: 0.9771 - 326ms/epoch - 4ms/step
Epoch 24/100
79/79 - 0s - loss: 0.0831 - accuracy: 0.9771 - val_loss: 0.1059 - val_accuracy: 0.9803 - 328ms/epoch - 4ms/step
Epoch 25/100
79/79 - 0s - loss: 0.0822 - accuracy: 0.9768 - val_loss: 0.1037 - val_accuracy: 0.9773 - 334ms/epoch - 4ms/step
Epoch 26/100
79/79 - 0s - loss: 0.0814 - accuracy: 0.9773 - val_loss: 0.1049 - val_accuracy: 0.9808 - 334ms/epoch - 4ms/step
Epoch 27/100
79/79 - 0s - loss: 0.0792 - accuracy: 0.9781 - val_loss: 0.1029 - val_accuracy: 0.9797 - 333ms/epoch - 4ms/step
Epoch 28/100
79/79 - 0s - loss: 0.0779 - accuracy: 0.9787 - val_loss: 0.1046 - val_accuracy: 0.9822 - 334ms/epoch - 4ms/step
Epoch 29/100
79/79 - 0s - loss: 0.0765 - accuracy: 0.9788 - val_loss: 0.1029 - val_accuracy: 0.9811 - 334ms/epoch - 4ms/step
Epoch 30/100
79/79 - 0s - loss: 0.0773 - accuracy: 0.9791 - val_loss: 0.1022 - val_accuracy: 0.9801 - 327ms/epoch - 4ms/step
Epoch 31/100
79/79 - 0s - loss: 0.0775 - accuracy: 0.9792 - val_loss: 0.1028 - val_accuracy: 0.9797 - 331ms/epoch - 4ms/step
Epoch 32/100
79/79 - 0s - loss: 0.0778 - accuracy: 0.9793 - val_loss: 0.1009 - val_accuracy: 0.9816 - 334ms/epoch - 4ms/step
Epoch 33/100
79/79 - 0s - loss: 0.0742 - accuracy: 0.9807 - val_loss: 0.0976 - val_accuracy: 0.9823 - 334ms/epoch - 4ms/step
Epoch 34/100
79/79 - 0s - loss: 0.0751 - accuracy: 0.9795 - val_loss: 0.0969 - val_accuracy: 0.9826 - 328ms/epoch - 4ms/step
Epoch 35/100
79/79 - 0s - loss: 0.0743 - accuracy: 0.9794 - val_loss: 0.0945 - val_accuracy: 0.9833 - 330ms/epoch - 4ms/step
Epoch 36/100
79/79 - 0s - loss: 0.0735 - accuracy: 0.9805 - val_loss: 0.1016 - val_accuracy: 0.9823 - 333ms/epoch - 4ms/step
Epoch 37/100
79/79 - 0s - loss: 0.0717 - accuracy: 0.9810 - val_loss: 0.1004 - val_accuracy: 0.9823 - 331ms/epoch - 4ms/step
Epoch 38/100
79/79 - 0s - loss: 0.0700 - accuracy: 0.9822 - val_loss: 0.0968 - val_accuracy: 0.9815 - 332ms/epoch - 4ms/step
Epoch 39/100
79/79 - 0s - loss: 0.0713 - accuracy: 0.9809 - val_loss: 0.0956 - val_accuracy: 0.9828 - 345ms/epoch - 4ms/step
Epoch 40/100
79/79 - 0s - loss: 0.0713 - accuracy: 0.9811 - val_loss: 0.0955 - val_accuracy: 0.9804 - 329ms/epoch - 4ms/step
Epoch 41/100
79/79 - 0s - loss: 0.0758 - accuracy: 0.9776 - val_loss: 0.0950 - val_accuracy: 0.9809 - 328ms/epoch - 4ms/step
Epoch 42/100
79/79 - 0s - loss: 0.0718 - accuracy: 0.9799 - val_loss: 0.0947 - val_accuracy: 0.9835 - 332ms/epoch - 4ms/step
Epoch 43/100
Restoring model weights from the end of the best epoch: 35.
79/79 - 0s - loss: 0.0700 - accuracy: 0.9818 - val_loss: 0.0938 - val_accuracy: 0.9829 - 333ms/epoch - 4ms/step
Epoch 43: early stopping